class AppConstants {
  static const String apiBaseUrl = 'https://dummyjson.com/';
  static const String apiLogin = 'auth/login';
  static const String apiAddCart = 'carts/add';
  static const String apiCarts = 'carts/';
  static const String apiPproducts = 'products';
  static const String apiCategories = 'products/category/';
  static const String apiSearch = "products/search";
  static const String search = "Search";
  static const String cart = "Cart";
  static const String profile = "Profile";
  static const String mostRecent = "Most Recent";
  static const String showAll = "Show All";
  static const String youMightAlsoLike = "You Might Also Like";
  static const String addToCart = "Add To Cart";
  static const String priceLowestToHeighest = "?sortBy=price&order=asc";
  static const String priceHeighestToLowest = "?sortBy=price&order=desc";
  static const String timeNewestToOldest = "?sortBy=title&order=desc";
  static const String timeOldestToNewest = "?sortBy=title&order=asc";
  static const String checkOutPage = "Check Out";
  static const String logOut = "Log Out";

  static const String userName = 'username';
  static const String password = 'password';
  static const String expiresInMins = 'expiresInMins';
  static const String message = "message";
  static const String oldestToNewest = "Oldest to Newest";
  static const String newestToOldest = "Newest to Oldest";
  static const String filterByDate =  "Filter by Date";
  static const String filterByPrice = "Filter by Price";
  static const String itemAddedToCart = "Item Added To Cart";
  static const String highestToLowest = "Highest to Lowest";
  static const String description = "Description";
  static const String lowestToHighest = "Lowest to Highest";
  static const String reviews = "reviews";
  static const String noItemsInCart = "No items in cart";
  static const String unKnownError = "Unknown error";
  static const String loginSuccess = "Login Successful";
  static const String signIn = "Sign in";
  static const String email = "Email";
  static const String passwordCapital = "Password";
  static const String enterEmail = "Please enter an email";
  static const String enterPassword = "Please enter a password";
  static const String userId = 'userId';
  static const String products = 'products';
  static const String failedToAddToCart = 'Failed to add to cart';
  static const String merge = 'merge';
  static const String total = "Total: ";
  static const String confirmOrder = 'Confirm Order';
  static const String orderConfirmed = "Order Confirmed";
  static const String newArrivalsJust = "New Arrivals Just";
  static const String forY = "For ";
  static const String you = "You";
  static const String userFiltersToViewProducts = "Use the filter to View Products!";
}
